modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="http://github.com/itsmeowCommissions/ToadTerror/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/toad-terror"
logoFile="logo.png"
credits="itsmeow for Programming, Proddy & Coda for art"
authors="itsmeow, Coda, Proddy"
license="All Rights Reserved"
[[mods]]
modId="toadterror"
version="${file.jarVersion}"
displayName="Toad Terror"
description='''
Adds a toad boss, structure, and protector.'''
[[dependencies.toadterror]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.toadterror]]
    modId="curios"
    mandatory=true
    versionRange="FORGE-1.16.[3,4]-[4.0.1.0,)"
    ordering="NONE"
    side="BOTH"